- README.md
`Trigger` component expects `popupAlign` instead of `align` (according to docs and code).
> Fixed prop name

- src/Trigger.jsx
- tests/index.js
This allow Trigger to render a popup as a function. It's particularly useful when you have hundreds of elements with tooltips and you don't want to generate all tooltips before they're triggered.
After merging this, I'll do the appropriate pull request on rc-tooltip to get the benefit of it.
> Allow render with popup as a function

- src/Trigger.jsx
> fix getPopupDomNode

- src/Trigger.jsx
这样调整可以方便写 Trigger 的测试，以 rc-select 的测试为例：
```javascript
const wrapper = mount(
<Select>
<Option value="1">1</Option>
</Select>
);
wrapper.find('.rc-select').simulate('click');
// 现在是找不到 MenuItem 的，因为被渲染到另外一个 container 上去了
wrapper.find('MenuItem');
```
如果把 getComponent 定义成 Trigger 的实例方法，就可以这样做：
```javascript
// 首先 mock 掉 ReactDOM 的 `unstable_renderSubtreeIntoContainer`
// 然后就可以自己手工去 mount Trigger 里的组件
const dropdownWrapper = mount(wrapper.find('Trigger').node.getComponent());
dropdownWrapper.find('MenuItem'); // 可以正常找到了。
```
这个 PR 需要先合并  https://github.com/react-component/util/pull/8
> 把 getComponent 定义在组件上

- package.json
Both rc-trigger and rc-align rely on rc-util but different versions, so end result is both version 3.x and 4.x are added to js bundle.
I've updated the rc-util version over in rc-align: https://github.com/react-component/align/pull/8
I've then removed rc-util as a dependency completely here in rc-trigger, since it is pulled in transitively. (Hope you are ok with that; it will help avoid this issue again in the future at least).
> Fix duplicate versions of rc-util in bundle

- src/Trigger.jsx
- tests/index.js
- tests/test.less
Will close https://github.com/ant-design/ant-design/issues/5047, fix bug introduced by #42 
---
负的 top 和 left 会使默认排版错乱。
改为 `top: 0; left: 0; width: 100%` 后正常。
- Error: http://codepen.io/anon/pen/LWENYG?editors=0110
- Fixed: http://codepen.io/anon/pen/qrEZWO?editors=0110
> fix text auto layout bug

- examples/nested.js
- examples/simple.js
- package.json
- src/LazyRenderBox.js
- src/Popup.jsx
- src/PopupInner.jsx
- src/Trigger.jsx
- tests/index.js
https://github.com/ant-design/ant-design/issues/5678
> fix react createClass and PropTypes warning

- src/Trigger.jsx
After https://github.com/react-component/trigger/commit/5337b189c9af2f21768d44dde127ebfc6020f22e, `this.popupInstance` has renamed to `this._component`.
This PR fixes 
https://github.com/ant-design/ant-design/issues/6085 
https://github.com/react-component/tree-select/issues/51
> this.popupInstance should be this._component

- .gitignore
- package.json
- src/Popup.js
Close: https://github.com/react-component/trigger/issues/56
Close: https://github.com/react-component/tooltip/issues/79
> fix: should re-align correctly when resize window, close: #56

- examples/nested.js
- src/Popup.js
- src/utils.js
- tests/index.js
As of React v16 using strings to create refs will no longer work. This is is forward looking change to address future compatibility issues as well as fixing existing deprecation warning thrown by react v15.
For more info on refs, see https://facebook.github.io/react/docs/refs-and-the-dom.html
> update react refs to use callback instead of string

- src/index.js
When using Inferno instead of React, I'm getting the following error when closing a dropdown:
Uncaught TypeError: this._component.getPopupDomNode is not a function
at Object.onPopupMouseLeave (index.js:178)
This change should fix the bug. I guess it's also related to https://github.com/ant-design/ant-design/issues/5701
> Make rc-trigger compatible with Inferno/Preact

- package.json
- src/Portal.js
- src/index.js
- tests/index.js
https://github.com/ant-design/ant-design/issues/5377#issuecomment-329682572
https://github.com/facebook/react/issues/10294#issuecomment-329479679
> Support React 16

- README.md
As per
https://github.com/react-component/trigger/blob/899e456b0d243a3b6da8960de9bf019b6ad52810/src/index.js#L65-L68
https://github.com/react-component/trigger/blob/899e456b0d243a3b6da8960de9bf019b6ad52810/src/index.js#L83-L86
`popupTransitionName` and `maskTransitionName`can be object as well as a string
> Update transitionName props in readme to reflect they can also be an Object

- src/Popup.js
* Remove `return null` since this will destroy the popup
* Add `setTime` to force `rc-align` to re-align the position since component not destroied
> Keep popup in the react dom

- src/Popup.js
- src/PopupInner.js
- src/index.js
- tests/basic.spec.js
ref: https://github.com/ant-design/ant-design/issues/9114
英文不太好描述，用中文了。
就是如果一个 Trigger 的 Popup 里面放了另一个 Trigger，这个子 Trigger 的Popup 被点击会导致父 Trigger 被关闭。
因为我们的外部点击监听是通过 `addEventListener` 触发，因而没有走 React 的生命周期。
现在增加一个 context 传递方法，当子 Trigger 的 Popup 被点击的时候，父 Trigger 的 context 方法被调用会临时锁定一下，这时通过 document 的 mouseDown 事件关闭被阻止：
另: rc-trigger 里的逻辑比较多，感觉需要找个时间整理一下。
> fix popup of trigger in another trigger click will cause parent trigger close

- examples/simple.js
- src/index.tsx
- tests/basic.test.jsx
Add an additional `try...catch...` to check throw with function component. If can not get DOM node by `ref` will fallback to use `findDOMNode(this)` to get the workable DOM node.
> feat: fallback to original findDOMNode if using function component

- .gitignore
- src/index.tsx
Ref: https://github.com/react-component/mentions/pull/18
> fix: ts type

- src/Popup.tsx
- tests/popup.test.jsx
See issue #157 
If the popup transitioned from visible to invisible before the status reached 'motion', the popup would get stuck in a visible state. This changes the code to immediately set status to 'stable'
during a transition from visible to invisible if the status is something before 'motion'.
Also fixes an issue where an animation frame could change the status to something invalid after a transition from visible to invisible.
> Fix motion popups sometimes getting stuck (#157)

- examples/simple.js
- src/index.tsx
- tests/basic.test.jsx
添加了`autoDestroy`属性，默认为`false`，和`destroyPopupOnHide`不同的是关闭后直接销毁Portal和子内容，`destroyPopupOnHide`只会删除Portal的子元素。
[#19536](https://github.com/ant-design/ant-design/issues/19536)
> feat: add autoDestroy prop(#19536);

- src/Popup.tsx
- tests/popup.test.jsx
横向快速移动鼠标，tooltip 会不消失：
https://codesandbox.io/s/beautiful-faraday-zfmgw?file=/index.js
原因在于 setState 是异步操作被 batch update，导致 motion 没有启动就被结束，而 Trigger 层以为已经触发了 motion 就继续执行锁逻辑导致 PopupInner 弹出后没人管的状态。
这个 fix 添加了一个额外的事件监听用于检查是否真的在进行动画。可能会有新 bug，随遇随修。
> fix: Motion state record

- examples/case.tsx
- src/Popup.tsx
- tests/util.test.jsx
fix https://github.com/ant-design/ant-design/issues/26241
Popup的status为null时，弹出的picker组件opacity为0，但鼠标依然可以选择上面的日期，导致了issue那个问题
> fix: component can still be selected when disabled

- examples/case.tsx
- package.json
- src/index.tsx
- tests/basic.test.jsx
`getPopupContainer` 的参数传入 `domNode` 产生了先有鸡还是先有蛋的问题。如果在渲染之后才触发 `getPopupContainer`，那么 `useEffect` 中就无法获取弹层内的节点：
```tsx
const someRef = useRef();
useEffect(() => {
console.log(someRef.current);
}, []);
return (
<Trigger
visible
getPopupContainer={(node) => node.parentNode}
popup={<div ref={someRef} />}
>
<button />
</Trigger>
);
```
如果先行渲染 `popup`，那么此时 `getPopupContainer` 的 dom 则还没有 ready。
现在做了如下改造，如果发现 `getPopupContainer` 没有 `triggerNode` 参数，则同时触发。如果有则异步触发。因而缩小冲突范围，只有在即用了 `triggerNode` 又使用 `popup[ref]` 的场景下会变成延迟触发。
ref https://codesandbox.io/s/eloquent-mclean-ss93m?file=/src/App.js
> fix: Patch for getPopupContainer check

- src/index.tsx
- tests/point.test.jsx
resolve https://github.com/ant-design/ant-design/issues/27058
> fix: Hide popup no need re-align

- assets/index.less
- assets/index/Mobile.less
- examples/simple.tsx
- package.json
- src/Popup/MobilePopupInner.tsx
- src/Popup/PopupInner.tsx
- src/Popup/index.tsx
- src/index.tsx
- src/interface.ts
- tests/__snapshots__/mobile.test.tsx.snap
- tests/mobile.test.tsx
https://github.com/react-component/trigger/blob/mobile/src/interface.ts#L67
> feat: Support mobile config

- src/index.tsx
use getRootDomNode() to find the correct document instead of using the default global one.
resolves https://github.com/ant-design/ant-design/issues/28165
> show popup at the same document as the trigger element

- package.json
- src/Popup/useVisibleStatus.ts
close https://github.com/ant-design/ant-design/issues/29328
close https://github.com/ant-design/ant-design/issues/27887
> fix: React state updated after component unmounted

- .eslintrc.js
- src/Popup/useVisibleStatus.ts
ref #240
`align` 状态更新是由 ResizeObserver 在 React 生命周期外控制，导致 effect 里清理会有时机问题。使用 ref 检查代替。
> fix: close motion not finished

- package.json
No css file included in the build package
https://github.com/react-component/trigger/issues/198
> chore(): Generate css

- src/index.tsx
- tests/basic.test.jsx
related issue:
https://github.com/ant-design/ant-design/issues/29853
I didn't check showAction or hideAction in isContextMenuOnly(), because when those 2 are defined, user might have very specific expectation about the mouse behavior, so I don't want to break existing code.
> fix: right click popup should be closed on mousedown target element

- src/index.tsx
close https://github.com/react-component/util/issues/293
> fix: prevent from creating multi portals

- src/index.tsx
- tests/basic.test.jsx
fix for `keepParent: false`, portal container should be attached to parent.
```tsx
<Tooltip
title="Antd Tooltip"
destroyTooltipOnHide={{ keepParent: false }}
>
<span>Antd Tooltip</span>
</Tooltip>
```
> fix: keep parent in strict mode

- src/Popup/PopupInner.tsx
- tests/motion.test.jsx
- tests/util.test.jsx
https://github.com/ant-design/ant-design/issues/35051#issuecomment-1101340714
消失的动画出不来，所以这个测试用例没补（消失时应该有 `pointer-events: none`），看上去需要 mock rc-motion ？
@zombieJ 看看
> fix: only disappearing elements should not be interactive

- src/Popup/PopupInner.tsx
- src/Popup/useVisibleStatus.ts
- tests/point.test.jsx
resolve https://github.com/ant-design/ant-design/issues/35197
`rc-align` 触发事件后，`rc-trigger` 本身做一个计数器。每次 align 后增加，重试 3 次后即进入下一个阶段。无论当前是否真的对齐到了预期位置。
antd 的问题在于对齐初期没有箭头，当对齐完毕后增加箭头，这个时候导致高度产生了变化让原本对齐的位置失效。过去为同步方法，在失效后进行重试，位置不再变化后进入下一个阶段。而在 React 18 StrictMode 下，同步执行由于不保证 forceAlign 导致成为了死循环。而改成异步 effect 后则不知道什么时候是最终对齐态。此处则增加一个 effect 计数器让数据流可以等待，并且最终会强制走到下一个阶段。
> fix: Align not waiting

- .fatherrc.js
- .github/workflows/main.yml
- jest.config.js
- package.json
- src/Popup/PopupInner.tsx
- tests/setup.js
`dom-align` 由于是 React 生命周期之外，性能越差的情况下越可能出现不同步的问题。加1次 retry times。
> chore: adjust retry times

- src/index.tsx
BuildInPlacements 定义被错误当成 export 实体到了 index.js 而不是只在 index.d.ts 里，诡异
> fix: TS export compile

- src/Popup/useStretchStyle.ts
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/38963
> fix: measure persion

- docs/examples/container.tsx
- src/hooks/useAlign.ts
- src/interface.ts
ref https://github.com/react-component/tooltip/issues/439
> feat: Add targetOffset back

- src/hooks/useAlign.ts
- src/index.tsx
- tests/align.test.tsx
> refactor: adjust popupAlign after placement to align with origin logic

- docs/examples/container.tsx
- src/hooks/useAlign.ts
- src/interface.ts
Support not auto adjust position when html has enough space for scroll
> feat: align support `htmlRegion` config

- docs/examples/container.tsx
- src/hooks/useAlign.ts
- tests/align.test.tsx
- tests/arrow.test.jsx
- tests/basic.test.jsx
resolve https://github.com/ant-design/ant-design/issues/41180
> chore: When target invisible, not trigger align

- docs/demos/body-overflow.md
- docs/examples/body-overflow.tsx
- src/hooks/useAlign.ts
antd 站点有个 body 的 `overflow: hidden` 导致计算可见区域的时候被裁剪：
https://ant.design/~demos/components-select-demo-basic
> chore: ignore body rect

- src/index.tsx
resolve https://github.com/ant-design/ant-design/issues/41261
ref 调用 setState 会触发 rerender，在快速切换时 React 18 会将 batch 合并，这使得 setState 的 prev 一直是 null 会让 React 认为是 `null -> node` 状态导致死循环。测试环境模拟不出来这种情况。比较蛋疼。
> fix: ref check to avoid loop

- docs/demos/large-popup.md
- docs/examples/large-popup.tsx
- src/hooks/useAlign.ts
- tests/flipShift.test.tsx
当同时开启 `overflow` & `shift` 时，会优先寻找最大区域，再进行滚动偏移：
> feat: support both `overflow` & `shift`

- docs/demos/static-scroll.md
- docs/examples/inside.tsx
- docs/examples/static-scroll.tsx
- src/hooks/useAlign.ts
- src/util.ts
- tests/flip.test.tsx
fix https://github.com/ant-design/ant-design/issues/41644
> fix: Area cal should skip static parent

- src/hooks/useAlign.ts
- tests/flip.test.tsx
当 Popup 在屏幕外时，可见面积是负数，优化至 0 以正常翻转。
> fix: adjustX + shiftX out of screen

- docs/examples/inside.tsx
- src/hooks/useAlign.ts
- tests/flip.test.tsx
弹层翻转后，如果后续调整位置同时满足 原位置 和 翻转位置 都放得下，则保持 翻转 以减少跳跃。
fix https://github.com/ant-design/ant-design/issues/41728
> feat: Stable popup align

- tests/basic.test.jsx
- tests/flip.test.tsx
CSSMiton 修复了不支持 动画 环境时，`onPrepare` 阶段会跳过的 BUG。同步更新一下对应的测试用例。
> test: fix align count test

- docs/examples/container.tsx
- src/index.tsx
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/42114
close https://github.com/ant-design/ant-design/pull/42107
> fix: Popup mouseDown inside and mouseUp outside should not close popup

- assets/index.less
- docs/examples/container.tsx
- src/Popup/Arrow.tsx
- src/Popup/index.tsx
- src/index.tsx
- src/interface.ts
- tests/arrow.test.jsx
Export arrow point as css variable, thus developer can dynamic set this with `transform-origin`
> feat: add arrow css var

- docs/demos/clip.md
- docs/examples/clip.tsx
- src/hooks/useAlign.ts
- src/util.ts
- tests/flip.test.tsx
fix https://github.com/ant-design/ant-design/issues/42220
> fix: Clip overflow calculation & rm position check

- .prettierrc
- docs/demos/visible-fallback.md
- docs/examples/visible-fallback.tsx
- src/hooks/useAlign.ts
- src/index.tsx
- src/interface.ts
- tests/flip-visibleFirst.test.tsx
- tests/flip.test.tsx
`visibleFirst` 模式下，会优先在视窗区域展示，其次降级为滚动区域展示。
> feat: add `visibleFirst`

- docs/examples/container.tsx
- src/hooks/useWinClick.ts
- src/index.tsx
- tests/basic.test.jsx
- tests/shadow.test.tsx
fix https://github.com/ant-design/ant-design/issues/42526
> fix: Click window should not immediately close if open is first time trigger

- docs/examples/body-overflow.tsx
- src/hooks/useWinClick.ts
- src/index.tsx
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/43202
> fix: contextMenu close all

- docs/examples/body-overflow.tsx
- src/index.tsx
- tests/basic.test.jsx
resolve https://github.com/ant-design/ant-design/issues/43527
当 Popup 关闭时，Hover 到 `createPortal` 创建的 dom 上不触发 `open` 逻辑。
> enhance: not reopen when closed

- src/hooks/useWatch.ts
- src/index.tsx
- tests/point.test.jsx
fix https://github.com/ant-design/ant-design/issues/44106
> fix: should hide popup when set alignPoint after scrolling

- docs/examples/inside.tsx
- src/hooks/useAlign.ts
- tests/flipShift.test.tsx
* 配置 `shift` 且超出屏幕的情况下，无论什么方向，始终应该是减去 `offset` 值。
* 当 `overflow` 配置且翻转的情况下，`offset` 也应该取反。
fix https://github.com/ant-design/ant-design/issues/44096
> fix: offsetX/Y on shift logic

- src/hooks/useAlign.ts
测量的时候创建一个占位元素把原本的位置顶住，测量完删除。
PS：这个在 jsdom 里无法测试出效果。
fix https://github.com/ant-design/ant-design/issues/44196
> fix: align not scrollable

- docs/examples/simple.tsx
- src/index.tsx
- tests/basic.test.jsx
在过去版本有个 queue 做状态管理，会确保在对齐前做一次 stretch 对齐，重写后这部分丢失。在 onPrepare 阶段补上对齐逻辑。
close https://github.com/react-component/trigger/pull/420
fix https://github.com/ant-design/ant-design/issues/44249
cc @bbb169
> fix: align jump for the first time render

- docs/examples/click-nested.tsx
- src/Popup/index.tsx
- src/index.tsx
- tests/basic.test.jsx
ref https://github.com/ant-design/ant-design/issues/44830
添加 fresh 支持，默认情况下 trigger 关闭时会缓存内容保持稳定。但是在极少数情况下需要让内容保持更新。
> feat: add fresh

- src/hooks/useAlign.ts
当 Popup 贴底做测量统计时，如果 Popup 有元素是超出 Popup 宽高的会导致游览器出现滚动条。而当回复原来位置后，滚动条消失导致偏了一个滚动条的尺寸。
ref https://github.com/ant-design/ant-design/issues/45784
> fix: cut logic of measure

- package.json
- src/index.tsx
- tests/portal.test.jsx
resolve https://github.com/ant-design/ant-design/issues/47093
> fix: Not trigger enter open for portal element

- src/hooks/useWinClick.ts
- tests/basic.test.jsx
- tests/shadow.test.tsx
ref https://github.com/ant-design/ant-design/issues/47671
看了一下过去行为，的确是 `mouseDown` 关闭更合理。调整一下事件，另外就是过去有一个 test 写的是元素 `stopPop` 可以让 Trigger 不关闭，之后又有一个 bug 是点击了 `stopPop` 元素时 Trigger 没有关闭。这两个本身是矛盾的，按照原生看以无论如何点击就关闭为准。
> refactor: Move hide event to `mouseDown`

- src/index.tsx
- tests/ref.test.tsx
顶层的 dom 外部无法获取，这使得关闭检测没有办法全包进去。透出一下：
ref https://github.com/ant-design/ant-design/issues/48249
> feat: support popupElement

- src/hooks/useAlign.ts
- tests/align.test.tsx
resolve #https://github.com/ant-design/ant-design/issues/48929
> enhance: Trigger use round position to fix precision

- docs/examples/shadow.tsx
- src/hooks/useWinClick.ts
- src/index.tsx
- tests/shadow.test.tsx
> Find element in multilevel shadows

- src/index.tsx
When setting `popupVisible` of a `<Trigger />` to true in a controlled manner, the popup is shown at 0,0 of the current page instead of being placed around its actual target. The reason for this is that the mouse position is initialized to 0, 0 and then passed along to `useAlign`.
This is a regression that was introduced in 848a197. In 7590937 this used to work and it had the exact logic I now re-added.
Within 848a197, the missing null initialization was introduced here:
https://github.com/react-component/trigger/commit/848a197f2236f6f5af94cc44e658bebae53837ae#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405R310
And here's the conditional passing of the point that was removed: https://github.com/react-component/trigger/commit/848a197f2236f6f5af94cc44e658bebae53837ae#di …
> fix: popup position for point-aligned popups when no mouse position is known

- src/Popup/index.tsx
- src/hooks/useWinClick.ts
- src/index.tsx
- tests/basic.test.jsx
ref https://github.com/react-component/trigger/issues/434
> fix: Use pointerDown to check if click with portal

- src/index.tsx
- tests/basic.test.jsx
> chore: compatible with legacy

- src/index.tsx
- tests/perf.test.tsx
初始化的时候，在不需要完全加载Popup的情况下，不加载Popup，以减少初始render所需要的时间。
这个更新已经在3.x里已经有了，但是在2.x里没有，所以加过来。
PS：3.x只用于antd的next分支及6.0的版本，2.x用于antd 5.x，当前antd6处于alpha1版本，我在5.x上遇到了这个性能问题
参考：
https://github.com/ant-design/ant-design/pull/53844
https://github.com/react-component/trigger/commit/052b2ae8b067daa0ab25527c9242dfa50d827aca
本地测试的情况：
机器：Mac M4 Pro 24G
测试方法：某个组件内包含Tooltip 150个，计算渲染时间
结果：
chrome 默认速度：4.5ms -> 3.2ms
chrome 6x slowdown：29ms -> 22ms
整体提升约25%
> perf: not render popup on init
