react-component/trigger

- examples/nested.js
- src/Trigger.jsx
- tests/index.spec.js
ref: https://github.com/ant-design/ant-design/issues/811
> Fix nested trigger

- src/LazyRenderBox.js
> Fix unknown prop warning

- src/Trigger.jsx
相关issue：https://github.com/ant-design/ant-design/issues/2384
> onPopupVisibleChange 增加event参数

- src/Trigger.jsx
Reverts react-component/trigger#23
> Revert "onPopupVisibleChange 增加event参数"

- README.md
Apologies if this is listed elsewhere, or obvious, but figured it was worth mentioning.
> Add required styling to README

- src/Trigger.jsx
close https://github.com/react-component/trigger/issues/41
> set default popup container to position absolute

- README.md
- src/Trigger.jsx
ref: https://github.com/ant-design/ant-design/issues/4041
所有基于 rc-trigger 的组件，Select DatePicker TimePicker 之类在跨 frame 调用时，都会有这个问题。
> feat: add Trigger[getDocument]

- src/Trigger.jsx
Close: https://github.com/ant-design/ant-design/issues/5804
> revert: should use touchstart and mousedown

- README.md
- package.json
- src/index.js
- tests/index.js
ref: https://github.com/ant-design/ant-design/issues/5586
> feat: support forceRender

- src/index.js
revert #71
---
close https://github.com/ant-design/ant-design/issues/8316
close https://github.com/ant-design/ant-design/issues/8397
> revert #71

- assets/index.less
- examples/nested.js
- examples/simple.js
- package.json
- src/LazyRenderBox.js
- src/Popup.js
- src/PopupInner.js
- src/index.js
- src/utils.js
- tests/basic.less
- tests/basic.spec.js
- tests/point.spec.js
Don't merge, still in process!
> Use CSSMotion instead of Animate

- src/index.js
close https://github.com/ant-design/ant-design/issues/17291
jsdom 行为和 Chrome 不一致，测不了。sad
> fix: Chrome label will auto focus inner input, prevent this

- package.json
- src/index.js
- tests/basic.spec.js
fix https://github.com/ant-design/ant-design/issues/17616
Use new life cycle method instead of call `this` variable directly.
> fix: afterPopupVisibleChange should trigger every time

- README.md
> fix: browser icons in readme

- .gitignore
- src/index.tsx
Reverts react-component/trigger#146
> Revert "fix: ts type"

- package.json
Ref: https://github.com/react-component/mentions/pull/18#issuecomment-543462477
> fix: npm publish files

- src/interface.ts
Ref: https://github.com/ant-design/ant-design/pull/19408
> add ignoreShake to AlignType

- package.json
- https://github.com/react-component/animate/blob/master/HISTORY.md#2102--2019-11-09
> fix lifecycle warning of rc-animate 

- .prettierrc
- examples/click-nested.js
- package.json
- src/index.tsx
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/20649
ref #98
> fix: Popup element with stopPropagation will make popup close

- src/Popup.tsx
- tests/basic.test.jsx
close https://github.com/ant-design/ant-design/issues/21770
> Fix popupStyle zIndex missing

- src/Popup.tsx
- tests/popup.test.jsx
Reverts react-component/trigger#188
> Revert "fix: Motion state record"

- src/Popup.tsx
- tests/popup.test.jsx
ref https://github.com/react-component/trigger/pull/188
修复递归问题
> fix: Motion state record

- examples/simple.js
- src/Popup.tsx
- src/PopupInner.tsx
fix https://github.com/ant-design/ant-design/issues/26000
把移除的任务交还给 CSSMotion
> fix: Motion End disappear should work

- src/Popup/useStretchStyle.ts
- src/index.tsx
ref: https://github.com/ant-design/ant-design/issues/26484
> chore: fix allowSyntheticDefaultImports define

- src/index.tsx
close https://github.com/ant-design/ant-design/issues/27621
close https://github.com/ant-design/ant-design-pro/issues/7567
https://github.com/react-component/trigger/pull/216/files#r518597886
> fix: remove console

- .gitignore
- package.json
> Add react and react-dom as peer dependencies

- .eslintrc.js
- examples/case.tsx
- examples/click-nested.js
- examples/nested.js
- examples/simple.tsx
- package.json
- src/Popup/Mask.tsx
- src/Popup/MobilePopupInner.tsx
- src/Popup/PopupInner.tsx
- src/Popup/index.tsx
- src/Popup/useStretchStyle.ts
- src/Popup/useVisibleStatus.ts
- src/index.tsx
- src/interface.ts
- src/utils/alignUtil.ts
- src/utils/legacyUtil.ts
- tsconfig.json
https://github.com/umijs/father/pull/311/
> upgrade father, fix eslint and prettier

- examples/nested.js
- src/Popup/PopupInner.tsx
- tests/basic.test.jsx
- tests/mask.test.jsx
- tests/mobile.test.tsx
- tests/motion.test.jsx
- tests/util.tsx
ref https://github.com/ant-design/ant-design/issues/30116
> fix:Support prevent close event children stopPropagation

- src/Popup/PopupInner.tsx
- tsconfig.json
https://github.com/ant-design/ant-design/issues/31717
> fix: should update placment className when change align

- src/index.tsx
Reverts react-component/trigger#292
> Revert "fix: prevent from creating multi portals"

- src/index.tsx
Reverts react-component/trigger#293
> fix: prevent from creating multi portals again

- src/Popup/MobilePopupInner.tsx
- src/Popup/PopupInner.tsx
- src/Popup/index.tsx
- src/index.tsx
- tests/basic.test.jsx
ref https://github.com/ant-design/ant-design/pull/35584#issuecomment-1140439339
> feat: Add onPopupClick event

- .gitignore
- README.md
- docs/demos/case.md
- docs/demos/click-nested.md
- docs/demos/nested.md
- docs/demos/point.md
- docs/demos/simple.md
- docs/index.md
- package.json
- tsconfig.json
- umirc.ts
> feat: dumi 1.x -> 2.x

- src/TriggerWrapper.tsx
- tests/basic.test.jsx
fix https://github.com/react-component/tooltip/issues/439
> fix: not ref if children not support

- src/index.tsx
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/41081
> fix: when popupVisible back to undefined, it should be false

- src/hooks/useAlign.ts
- tests/align.test.tsx
ref https://github.com/react-component/tooltip/issues/444
> fix: popupAlign not merge into builtinPlacement

- package.json
- src/hooks/useAlign.ts
- src/index.tsx
- tests/align.test.tsx
fix https://github.com/react-component/tooltip/issues/444
> fix: support svg

- docs/examples/container.tsx
- src/hooks/useAlign.ts
- tests/flip.test.tsx
fix https://codesandbox.io/s/eager-bash-3f44os?file=/App.tsx
> fix: Only flip if space is enough

- docs/examples/body-overflow.tsx
- src/hooks/useAction.ts
- src/index.tsx
- tests/mobile.test.tsx
ref https://github.com/ant-design/ant-design/issues/41260
> chore: auto change handler

- src/hooks/useAlign.ts
fix https://github.com/ant-design/ant-design/issues/41377
> fix: refactor missing default value

- docs/demos/shadow.md
- docs/examples/shadow.tsx
- package.json
- src/index.tsx
- tests/shadow.test.tsx
fix https://github.com/ant-design/ant-design/issues/41428
> fix: ShadowDOM click interactive

- src/index.tsx
get error subPopupEle maybe null
> update trigger function inPopupOrChild

- src/Popup/PopupContent.tsx
- src/Popup/index.tsx
- tests/motion.test.jsx
发布后验证一下看看好没好再关
ref https://github.com/ant-design/ant-design/issues/41810
> chore: cache content when closing

- src/Popup/Arrow.tsx
- src/Popup/index.tsx
- src/index.tsx
- src/interface.ts
- tests/arrow.test.jsx
prepare for https://github.com/react-component/tooltip/issues/448
> feat: arrow add className support

- src/Popup/Mask.tsx
- src/hooks/useAlign.ts
- src/interface.ts
- tests/align.test.tsx
- tsconfig.json
fix https://github.com/ant-design/ant-design/issues/41992
fix #354
> feat: offset support ptg and fix targetOffset logic

- src/hooks/useWinClick.ts
> chore: adjust to fit ie

- package.json
- src/index.tsx
Can not mock shadow order with jsdom. Let's release alpha for test.
> fix: align with shadow

- src/hooks/useWinClick.ts
Shadow test 模拟没意义，真是蛋疼。
fix https://github.com/ant-design/ant-design/issues/42936
> fix: gen func instead

- docs/examples/inside.tsx
- src/Popup/index.tsx
- src/hooks/useAlign.ts
- src/index.tsx
- src/interface.ts
- tests/align.test.tsx
会根据 `align` 位置自动选择是通过 `left | right` or `top | bottom` 进行定位，以优化从上方打开时高度变化引起的跳动问题。
防止 breaking change，需要配置开启。
> feat: autoAlign pos

- src/hooks/useWinClick.ts
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/43093
fix https://github.com/ant-design/ant-design/issues/43685
> fix: should hide when click outside stopPropagation button

- src/Popup/index.tsx
- src/index.tsx
- tests/basic.test.jsx
fix https://github.com/ant-design/ant-design/issues/43924
感叹 `pointerEvent` 真是伟大的发明，again
> enhance: hover disabled component not to hide

- src/interface.ts
> chore: compatible for api def

- src/index.tsx
- tests/ref.test.tsx
ref https://github.com/ant-design/ant-design/issues/45541
> feat: trigger support nativeElement

- src/hooks/useAlign.ts
https://github.com/react-component/trigger/pull/437/files#r1390671613
> chore: clean up

- src/mock.tsx
- tests/basic.test.jsx
- tests/motion.test.jsx
close https://github.com/react-component/trigger/security/code-scanning/1
close https://github.com/react-component/trigger/security/code-scanning/2
close https://github.com/react-component/trigger/security/code-scanning/3
> fix: code scanning alerts
